name: Repogent AI Automation

on:
  pull_request:
  issues:
  issue_comment:

jobs:
  repogent:
    runs-on: ubuntu-latest
    steps:
      - name: Run Repogent
        uses: vijayabhaskar78/Repogent@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          groq-key: ${{ secrets.GROQ_API_KEY }}
